// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_template/core/constants/environments.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: Environments.FIREBASE_WEB_API_KEY,
    appId: Environments.FIREBASE_APP_ID,
    messagingSenderId: Environments.FIREBASE_MESSAGING_SENDER_ID,
    projectId: Environments.FIREBASE_PROJECT_ID,
    authDomain: Environments.FIREBASE_AUTH_DOMAIN,
    storageBucket: Environments.FIREBASE_STORAGE_BUCKET,
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: Environments.FIREBASE_ANDROID_API_KEY,
    appId: Environments.FIREBASE_APP_ID,
    messagingSenderId: Environments.FIREBASE_MESSAGING_SENDER_ID,
    projectId: Environments.FIREBASE_PROJECT_ID,
    storageBucket: Environments.FIREBASE_STORAGE_BUCKET,
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: Environments.FIREBASE_IOS_API_KEY,
    appId: Environments.FIREBASE_APP_ID,
    messagingSenderId: Environments.FIREBASE_MESSAGING_SENDER_ID,
    projectId: Environments.FIREBASE_PROJECT_ID,
    storageBucket: Environments.FIREBASE_STORAGE_BUCKET,
    iosBundleId: Environments.FIREBASE_IOS_BUNDLE_ID,
  );

}
