name: Build and Distribute

on:
  push:
    branches:
      - feature/refactor-template

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Grant execute permission for increment_version.sh
        run: chmod +x ./scripts/increment_version.sh

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Increment version number
        run: ./scripts/increment_version.sh

      - name: Build APK
        run: flutter build apk --flavor development --profile --dart-define-from-file=env/dev.json  

      - name: Get changelog diff
        run: |
          last_commit=$(git rev-parse HEAD~1)

          git diff "$last_commit" HEAD -- CHANGELOG.md > changelog_diff.txt || echo "No hay cambios en CHANGELOG.md"

          if [ -s changelog_diff.txt ]; then
            echo "::set-output name=changelog::$(cat changelog_diff.txt)"
          else
            echo "No hay cambios en CHANGELOG.md"
            echo "" > changelog_diff.txt  # Crear un archivo vacío si no hay cambios
            echo "::set-output name=changelog::''"  # Salida vacía si no hay cambios
          fi

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: build/app/outputs/flutter-apk/app-development-profile.apk
          releaseNotes: "${{ steps.get_changelog_diff.outputs.changelog }}"
          releaseNotesFile: CHANGELOG.md
        